server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver



  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create


    show-sql: true

  database-platform=org:
    hibernate:
      dialect:
        H2Dialect:

  h2:
    console:
      enabled: true
      path: /h2